project:
  type: book

book:
  title: "My Book with Bookly"
  author: "First Last"
  date: today
  output-file: "my-book-bookly"
  chapters:
    - index.qmd
    - part: "First part"
      chapters:
        - chapters/intro.qmd
        - chapters/methods.qmd
    - part: "Second part"
      chapters:
        - chapters/results.qmd
        - chapters/discussion.qmd
  appendices:
    - appendices/appendixA.qmd

format:
  bookly-typst:
    fonts:
      body: "Lato"
      math: "Lete Sans Math"
    lang: en
    toc: true
    lof: true
    lot: true
    keep-typ: true
    theme: fancy      # classic | modern | fancy | obook | orly | pretty
    tufte: true       # set to true to enable Tufte layout
    config-options:
      open-right: true        # chapters start on right-hand pages
      alt-margins: false      # alternating margins (recto/verso)
    # part-numbering: "A" # part numbering style (e.g. "1", "A", "I")
    # colors:
    #   primary: "rgb(\"#1d90d0\")"
    #   secondary: "rgb(\"#dddddd\").darken(15%)"
